stages:
  - build
  - test
  - analyze
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  SONAR_TOKEN: "$SONAR_TOKEN" # from GitLab CI/CD ENVIRONMENT

before_script:
  - bundle install

build_ios:
  stage: build
  script:
    - fastlane ios build

build_android:
  stage: build
  script:
    - fastlane android build

test_ios:
  stage: test
  script:
    - fastlane ios test

test_android:
  stage: test
  script:
    - fastlane android test

analyze:
  stage: analyze
  script:
    - fastlane run swiftlint
    - fastlane run ktlint

sonarqube_scan:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.organization=dhec_key -Dsonar.sources=./src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  allow_failure: true

deploy_beta:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $RELEASE_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TITLE =~ /Merge branch.*/'
    - if: '$CI_COMMIT_BRANCH == $RELEASE_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null'
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $RELEASE_BRANCH'
  script:
    - fastlane ios beta
    - fastlane android beta
  when: manual
 
